---
- name: Checkout the repo
  git:
    repo: "{{ git_repo }}"
    dest: "roles/deploy/files/repo"
    version: "{{ git_repo_branch }}"
  delegate_to: 127.0.0.1

- name: Build image and with buildargs
  docker_image:
     path: "roles/deploy/files/repo"
     name: "{{ docker_image_name }}"
     tag: v1
  delegate_to: 127.0.0.1

- name: Archive image
  docker_image:
    name: "{{ docker_image_name }}"
    tag: v1
    archive_path: "roles/deploy/files/{{ docker_image_name }}.tar"
  delegate_to: 127.0.0.1

- name: Transfer image tar to remote destination 
  remote_user: ubuntu
  become: true
  become_user: root
  copy:
    src: "roles/deploy/files/{{ docker_image_name }}.tar"
    dest: /home/ubuntu/

- name: Load image
  remote_user: ubuntu
  become: true
  become_user: root
  shell: "sudo docker load -i /home/ubuntu/{{ docker_image_name }}.tar"


- name: Create the container
  remote_user: ubuntu
  become: true
  become_user: root
  shell: sudo docker run -d -p "80:3000" -e "DYNAMODB_TABLE={{ table_name }}" -e "REDIS_SERVER={{ redis_server }}" -e "AWS_REGION={{ region }}" --name "{{ container_name }}v2" "{{ docker_image_name }}"
