---
- name: ensure repository key is installed
  become: true
  become_user: root
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

- name: ensure docker registry is available
  become: true
  become_user: root
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: ensure docker and dependencies are installed
  become: true
  become_user: root
  apt: name=docker-engine update_cache=yes

- name: start the deamon
  become: true
  become_user: root
  service: name=docker state=restarted

