---
- name: Create DynamoDB 
  dynamodb_table:
    name: "{{ table_name }}"
    region: "{{ db_region }}"
    hash_key_name: "{{ key_name }}"
    hash_key_type: "{{ key_type }}"
    read_capacity: "{{ r_capacity }}"
    write_capacity: "{{ w_capacity }}"
