---
- name: Create Redis cluster
  elasticache:
    name: "{{ redis_cluster_name }}"
    state: present
    engine: redis
    cache_engine_version: "{{ redis_version }}"
    node_type: "{{ redis_node_type }}"
    num_nodes: "{{ redis_num_nodes }}" 
    cache_port: "{{ redis_port }}"
    region: "{{ redis_region }}"
    zone: "{{ redis_zone }}"
