---
  # - name: Provision Redis
  #   hosts: local
  #   connection: local
  #   gather_facts: False
  #   tags: provisioning
  #   # Necessary Variables for creating/provisioning the EC2 Instance
  #   vars:
  #     table_name: cmp-devops-redis
  #     aws_account: 784645331409
  #     #redis_arn: "arn:aws:dynamodb:{{ db_region }}:{{ aws_account }}:table/{{ table_name }}"
  #     redis_region: us-east-1
  #     vpc_subnet_id: subnet-0391fb2e

    tasks:
      - name: Create Redis cluster
        elasticache:
          name: "cmp-redis-dev"
          state: present
          engine: redis
          cache_engine_version: 3.2.4
          node_type: cache.m1.small
          num_nodes: 1
          cache_port: 6379
          region: us-east-1
          zone: us-east-1d